stages:
  - build
  - test
  # - deploy

variables:
  MAVEN_CLI_OP: "clean"

build:
  stage: build
  script:
    - cd server
    - mvn $MAVEN_CLI_OP compile
  artifacts:
    paths:
      - output
  tags:
    - ugrad

test:
  stage: test
  script:
    - cd server
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

# Reference: https://docs.gitlab.com/ee/ci/ssh_keys/
# deploy:
#   stage: deploy
#   image: maven:latest
#   before_script:
#     - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
#     - eval $(ssh-agent -s)
#     - echo -n "$DEPLOY_SSH_KEY"

#   script:
#     - cd server
#     - echo "Starting the deploy script"
#     - chmod 400 ${DEPLOY_SSH_KEY}
#     - zip -v -r output_compressed.zip . -i output
#     - scp -r -v output_compressed.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/output_compressed.zip"
#     - echo "Deploy Success"
#   tags:
#     - ugrad
#   only:
#     - cd-test
