stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OP: "clean"

build:
  stage: build
  script:
    - cd server
    - mvn $MAVEN_CLI_OP compile
  artifacts:
    paths:
      - output
  tags:
    - ugrad

test:
  stage: test
  script:
    - cd server
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

deploy:
  stage: deploy
  image: maven:latest
  before_script:
    - apt-get update -y && apt-get install openssh-client -y
    - eval $(ssh-agent)
  script:
    - echo "Starting the deploy script"
    - zip -r output.zip output
    - scp -r -v -o StrictHostKeyChecking=no output.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/output.zip"
    - echo "Deploy Success"
  tags:
    - ugrad
  only:
    - develop
