stages:
  - builddbdev
  - builddbtest
  - builddbdprod
  - testdbdev
  - testdbtest
  - testdbprod
  - deploy

variables:
  MAVEN_CLI_OP: "clean"

### Only on develop ### Use 'dev' DBConfig
builddbdev:
  stage: builddbdev
  script:
    - cd server
    - echo "Building with Maven"
    - mvn $MAVEN_CLI_OP package -Pdev
  artifacts:
    paths:
      - server/target
  tags:
    - ugrad
  only:
    - develop

testdbdev:
  stage: testdbdev
  script:
    - cd server
    - echo "Testing..."
    - mvn verify -Pdev
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad
  only:
    - develop

## Only on master ### Use 'production' DBConfig
builddbdprod:
  stage: builddbdprod
  script:
    - cd server
    - echo "Building with Maven"
    - mvn $MAVEN_CLI_OP package -Pproduction
  artifacts:
    paths:
      - server/target
  tags:
    - ugrad
  only:
    - master

testdbprod:
  stage: testdbprod
  script:
    - cd server
    - echo "Testing..."
    - mvn verify -Pproduction
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad
  only:
    - master

# Reference: https://docs.gitlab.com/ee/ci/ssh_keys/
deploy:
  stage: deploy
  image: maven:latest
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
  script:
    - cd server
    - echo "Starting the deploy script"
    - chmod og-rwx ${DEPLOY_SSH}
    - zip -v -r output_compressed.zip target
    - scp -r -v -o StrictHostKeyChecking=no -i "${DEPLOY_SSH}" output_compressed.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/DeployMaster-${CI_COMMIT_SHORT_SHA}.zip"
    - echo "Deploy Success"
  tags:
    - ugrad
  only:
    - master

### All Other Branches ### Use 'test' DBConfig
builddbtest:
  stage: builddbtest
  script:
    - cd server
    - echo "Building with Maven"
    - mvn $MAVEN_CLI_OP package -Ptest
  artifacts:
    paths:
      - server/target
  tags:
    - ugrad
  except:
    - develop
    - master

testdbtest:
  stage: testdbtest
  script:
    - cd server
    - echo "Testing..."
    - mvn verify -Ptest
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad
  except:
    - develop
    - master
