stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OP: "clean"

build:
  stage: build
  script:
    - cd server
    - echo "Building with Maven"
    - mvn $MAVEN_CLI_OP compile
  artifacts:
    paths:
      - target
  tags:
    - ugrad

test:
  stage: test
  script:
    - cd server
    - echo "Testing..."
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

deploy:
  stage: deploy
  image: maven:latest
  before_script:
    - eval $(ssh-agent)
  script:
    - cd server
    # https://docs.gitlab.com/ee/ci/ssh_keys/
    - echo "$DEPLOY_SSH_KEY
    " | tr -d '\r' | ssh-add -
    - echo "Starting the deploy script"
    - zip -v -r output_compressed.zip . -i output
    - scp -r -v -o StrictHostKeyChecking=no output_compressed.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/output_compressed.zip"
    - echo "Deploy Success"
  tags:
    - ugrad
  only:
    - cd-test
