stages:
  - build
  - test

variables:
  MAVEN_CLI_OP: "clean"

server:
  stage: build
  script:
    - cd server
    - mvn $MAVEN_CLI_OP compile
  tags:
    - ugrad

client:
  stage: test
  script:
    - cd server
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad
