stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OP: "clean"

build:
  stage: build
  script:
    - cd server
    - echo "Building with Maven"
    - mvn $MAVEN_CLI_OP compile
  artifacts:
    paths:
      - target
  tags:
    - ugrad

test:
  stage: test
  script:
    - cd server
    - echo "Testing..."
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - server/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad
